app/controllers/ApiController.php
<?php

namespace app\controllers;

use app\components\ForksSeeker\ForksSeeker;
use app\components\Grabber\Grabber;
use app\components\Helpers\BookmakerHelper;
use app\components\Helpers\ParamsHelper;
use app\components\ParticipantsMatcher\ParticipantMatcher;
use app\repositories\MatchRepository;
use PDO;
use Yii;
use yii\db\Exception;
use yii\db\Query;
use yii\rest\Controller;
use yii\web\Response;
use function array_merge;
use function base64_encode;
use function class_exists;
use function file_exists;
use function file_get_contents;
use function file_put_contents;
use function in_array;
use function ucfirst;

/**
 * Class ApiController
 * @package app\controllers
 */
class ApiController extends Controller
{
    private array $params;

    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);

        $this->params = Yii::$app->params;
    }

    public function actionTest(): array
    {
        return [];
    }

    /**
     * @return array
     * @throws Exception
     */
    public function actionIndex(): array
    {
        $betfairMatchCollection  = (new MatchRepository())->getLastMatchesByBookmaker(BookmakerHelper::BETFAIR_BOOKMAKER_ID);
        $pinnacleMatchCollection = (new MatchRepository())->getLastMatchesByBookmaker(BookmakerHelper::PINNACLE_BOOKMAKER_ID);
        $sbobetMatchCollection   = (new MatchRepository())->getLastMatchesByBookmaker(BookmakerHelper::SBOBET_BOOKMAKER_ID);

        $participantMather = new ParticipantMatcher();
        $participantMather->prepare();

        $forksSeeker = new ForksSeeker($participantMather);
        $forks       = $forksSeeker->seek([
            $betfairMatchCollection,
            $pinnacleMatchCollection,
            $sbobetMatchCollection,
        ]);

        Yii::$app->getResponse()->format = Response::FORMAT_JSON;

        $allMatches = array_merge(
            $betfairMatchCollection->getAll(),
            $pinnacleMatchCollection->getAll(),
            $sbobetMatchCollection->getAll()
        );

        foreach ($forks as $fork) {
            foreach ($allMatches as $key => $match) {
                if (in_array($match, $fork, true)) {
                    unset($allMatches[$key]);
                }
            }
        }

        $notAllocatedMatches = [];
        foreach ($allMatches as $match) {
            $notAllocatedMatches[$match->getBookmakerId()][] = $match;
        }

        $bookmakers = (new Query())
            ->select(['id', '*'])
            ->from('bookmaker')
            ->createCommand()
            ->queryAll([PDO::FETCH_UNIQUE | PDO::FETCH_ASSOC]);

        $sports = (new Query())
            ->select(['id', '*'])
            ->from('sport')
            ->createCommand()
            ->queryAll([PDO::FETCH_UNIQUE | PDO::FETCH_ASSOC]);

        return [
            'notAllocatedMatches' => $notAllocatedMatches,
            'forks'               => $forks,
            'dictionary'          => [
                'bookmakers' => $bookmakers,
                'sports'     => $sports,
            ],
        ];
    }

    /**
     * @return array|string[]
     */
    public function actionLastGrabbed(): array
    {
        $betfairFile  = Yii::getAlias('@runtime') . '/files/betfair_screenshot.png';
        $pinnacleFile = Yii::getAlias('@runtime') . '/files/pinnacle_screenshot.png';

        $betfairScreenshot  = null;
        $pinnacleScreenshot = null;

        if (file_exists($betfairFile)) {
            $screenshot        = file_get_contents($betfairFile);
            $betfairScreenshot = 'data:image/png;base64,' . base64_encode($screenshot);
        }

        if (file_exists($pinnacleFile)) {
            $screenshot         = file_get_contents($pinnacleFile);
            $pinnacleScreenshot = 'data:image/png;base64,' . base64_encode($screenshot);
        }

        return [
            'betfairScreenshot'  => $betfairScreenshot,
            'pinnacleScreenshot' => $pinnacleScreenshot,
        ];
    }
}

app/controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\Parser\Parser;
use app\repositories\MatchRepository;
use Yii;
use yii\web\Controller;
use function class_exists;
use function file_get_contents;
use function ucfirst;

/**
 * Class SiteController
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $bookmakerName = 'pinnacle';

        $file = file_get_contents(Yii::getAlias('@runtime') . "/files/$bookmakerName.html");

        $parserStrategyFullClassName = 'app\\components\\Parser\\ParserStrategy\\' . ucfirst($bookmakerName) . 'ParserStrategy';
//        if (!class_exists($parserStrategyFullClassName)) {
//            continue;
//        }

        $parser                = new Parser(new $parserStrategyFullClassName);
        $parsedMatchCollection = $parser->parse($file);

        (new MatchRepository())->save($parsedMatchCollection);

        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionLastGrabbed(): string
    {
        return $this->render('last-grabbed');
    }
}

app/views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl'   => Yii::$app->homeUrl,
        'options'    => [
            'class' => 'navbar navbar-dark bg-dark navbar-expand-lg fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items'   => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Last Grabbed', 'url' => ['/site/last-grabbed']],
            ['label' => 'Participants', 'url' => ['/participant/default/index']],
            ['label' => 'Bookmakers', 'url' => ['/bookmaker/default/index']],
            ['label' => 'Sports', 'url' => ['/sport/default/index']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

app/views/site/last-grabbed.php
<div id="app">
    <img v-bind:src="data.betfairScreenshot" alt="pinnacleScreenshot">
    <img v-bind:src="data.pinnacleScreenshot" alt="betfairScreenshot">
</div>

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script>
    let app = new Vue({
        el     : '#app',
        data   : {
            data: null
        },
        methods: {
            getData() {
                axios.get('/api/last-grabbed')
                    .then(response => this.data = response.data)
            },
        },
        mounted() {
            this.getData();
        }
    })
</script>